# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-29 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20180901_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copypath', models.CharField(default=b'', max_length=255)),
                ('copyname', models.CharField(default=b'', max_length=255)),
                ('originalpath', models.CharField(max_length=255)),
                ('originalname', models.CharField(max_length=255)),
                ('contenthash', models.CharField(max_length=64)),
                ('pathhash', models.CharField(max_length=64)),
                ('sender', models.CharField(default=b'', max_length=255)),
                ('reciever', models.CharField(max_length=255)),
                ('ekey', models.CharField(default=b'', max_length=255)),
                ('linkidentifier', models.CharField(default=b'', max_length=255)),
                ('linkpassword', models.CharField(default=b'', max_length=255)),
                ('viewed', models.BooleanField(default=False)),
                ('linkcount', models.CharField(default=b'0', max_length=1)),
                ('shareddate', models.DateTimeField()),
                ('expirylength', models.CharField(max_length=5)),
                ('expirydate', models.DateTimeField()),
            ],
            options={
                'ordering': ['-expirydate'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='sharedrecord',
            unique_together=set([('linkidentifier',)]),
        ),
    ]
