# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-30 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20190629_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedrecord',
            name='ekey',
            field=models.TextField(default=b'', max_length=255),
        ),
    ]
