# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-30 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20190630_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedrecord',
            name='ekey',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
